# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 980e0283d425c9bb40ef8830a7949703ed91eaf6ad148a97d3ac3b2a6767b76818dced435f6aab9ca6c2f1a58841e8be715739c18701e85ec80c057475cd4c60

test:
  secret_key_base: ef383444a2c7fd1f13db7fb5ec3c44c6f09dad1e9ac13c304298eb3123902580eeb9252c07e65d7418fe80259e2a5194f2cdfd691810620bc8c431e9b42ab2c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
